<?php

/**
 * Корень: код поставщика
 * Содержит массив - маппинг (слева прайс значение, справа tecdoc)
 */

return [
    'shate' => [
        'BLUEPRINT' => 'BLUE PRINT',
        'LEMFOERDER' => 'LEMFÖRDER',
        'REINZ' => 'VICTOR REINZ',
        'BORGWARNER' => 'BorgWarner',
        'LUK' => 'LuK',
        'METALCAUCHO' => 'Metalcaucho',
        'NIBK' => 'NiBK',
        'STARTVOLT' => 'StartVOLT',
    ],
    'monlibon' => [
        'CHAMPION OIL' => 'CHAMPION LUBRICANTS',
        'FEBI' => 'FEBI BILSTEIN',
        'LEMFORDER' => 'LEMFÖRDER',
        'REINZ' => 'VICTOR REINZ',
        'G.U.D' => 'G.U.D.',
    ],
    'armtek' => [
        'AS-METAL' => 'AS METAL',
        'AUTOFREN' => 'AUTOFREN SEINSA',
        'AVA' => 'AVA QUALITY COOLING',
        'CARGO' => 'CARGOPARTS',
        'BORG WARNER' => 'BorgWarner',
        'GUD' => 'G.U.D.',
        'FEBI' => 'FEBI BILSTEIN',
        'FOMAR' => 'FOMAR Friction',
        'LESJOFORS' => 'LESJÖFORS',
        'LMI' => 'LEMFÖRDER',
        'LOBRO' => 'LÖBRO ',
        'MAHLE' => 'MAHLE ORIGINAL',
        'MANDO' => 'Maysan Mando',
        'MEC ARM' => 'MECARM',
        'NEOLUX' => 'NEOLUX®',
        'RECORD' => 'RECORD FRANCE',
        'POLMOSTROW' => 'POLMO',
        'AKITAKA' => 'ASVA',
        'AS' => 'AS-PL',
        'BEHR' => 'BEHR HELLA SERVICE',
        'CLEAN' => 'CLEAN FILTERS',
        'DIAMOND' => 'DPA',
        'DYNAMAX' => 'DYNAMATRIX',
        'FAST' => 'FAST TIGER',
        'GOETZE' => 'GOETZE ENGINE',
        'HERTH+BUSS' => 'HERTH+BUSS JAKOPARTS',
        'IMPERGOM' => 'ORIGINAL IMPERIUM',
        'INTER BRAKES' => 'CAR',
        'JP' => 'JP GROUP',
        'MALO' => 'MALÒ',
        'NURAL' => 'NÜRAL',
        'PE' => 'PE AUTOMOTIVE',
        'SCT' => 'SCT Germany',
        'SE-M' => 'SEM LASTIK',
        'TRUCKTEC' => 'TRUCKTEC AUTOMOTIVE',
        'VERNET' => 'CALORSTAT by Vernet',
    ],
    'avtospace' => [
        'ASMETAL' => 'AS METAL',
        'GUD' => 'G.U.D.',
        'LEMFORDER' => 'LEMFÖRDER',
    ],
    'sviat' => [
        'ASMETAL' => 'AS METAL',
        'GUD' => 'G.U.D.',
        'FEBI' => 'FEBI BILSTEIN',
        'LEMFORDER' => 'LEMFÖRDER',
    ],
    'motex' => [
        'POLMO' => 'POLMOSTROW',
        'REINZ' => 'VICTOR REINZ',
        'LEMFORDER' => 'LEMFÖRDER',
        'MEAT&DORIA' => 'MEAT & DORIA',
        'KROON-OIL' => 'KROON OIL',
        'CARGO' => 'CARGOPARTS',
        'FAI' => 'FAI AutoParts',
        'AS-METAL' => 'AS METAL',
        'AVA' => 'AVA QUALITY COOLING',
    ],
    'lauto' => [
        'AKS' => 'AKS DASIS',
        'COOPERSFIAAM FILTERS' => 'CoopersFiaam',
        'DYNAMATRIX-KOREA' => 'DYNAMATRIX',
        'DYNAMAX-KOREA' => 'DYNAMAX',
        'NURAL' => 'NÜRAL',
        'NEOLUX' => 'NEOLUX®',
        'POLMOSTROW' => 'POLMO',
        'G.U.D' => 'G.U.D.',
        'MALO' => 'MALÒ',
        'Mando' => 'Maysan Mando',
        'LESJOFORS' => 'LESJÖFORS'
    ]
];
